---
grails:
    profile: rest-api
    codegen:
        defaultPackage: org.transmart.api.server
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    url: jdbc:postgresql://localhost:5432/transmart
    driverClassName: org.postgresql.Driver
    username: biomart_user
    password: biomart_user
    dbCreate: none
    pooled: true
    jmxExport: true
    logSql: false
    formatql: false
    properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

grails:
    cors:
        enabled: true
        allowedOrigins:
            - http://localhost:4200

server:
  port: 8081

security:
    oauth2:
        client:
            clientId: client_1
#        resource:
#            userInfoUri: http://localhost:8080/auth/realms/transmart/protocol/openid-connect/userinfo

#keycloak:
#    enable-basic-auth: false  # basic auth is default true, we dont want that
#    realm: transmart   # our keycloak realm this ressource service should be based in
#    auth-server-url: http://localhost:8080/auth  # the url to our sso server (keycloak)
#    ssl-required: external  # no ssl is ok for demo  - do not use this in production
#    resource: tm_client  # the realm-client which accessing clients should be authenticate with
#    use-resource-role-mappings: true # use this if you manage your roles in client scope not in realm scope
#    public-client: false # we do not write a web-app - so no login page and redirects are necessary
#    bearer-only: true  # authentification via accesstoken is fine
#    credentials:
#        secret: 7034b121-fdf1-4188-9ba2-c66bee4b9867

