language: groovy
jdk:
- oraclejdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: kjaLOzq+j1DlyxR1mHxg2ovSaBiFpXLVWFYAGDly4a2z/rQy7CY+rPPVegKxWejyNS23/8/OYfd3dEtu5+7X95S12x2GxECD3l8TX3J7g451plL4wo7yL8vu6uPUA0i4IKrUpLlWUS6v9ht4tV5ylvsN7NqKn+lSvzAgRImuMr4=
  - secure: daUXlpHA7jo6ApL7E4Z9K8ABQFHCleQqbDFRaehMmrWl3Hma0RuRPj0gWjH99tu6mMRYglOuH9H23CLvjlMltIvy3nnKjftKHe/o+3cmKyWkD/CX1SWFghdb7qUn/Er2sfKoGXkLJnLqUzPMaqSdZ5euZIlxj0p08uYBUGeYSyY=
  - secure: uWk4Yo/8bDcbsTWGW7Lrbjmys3pWZN9qvN9AOR+UXacNMK9D7wXgKMGOX2NVdJWraIS6MSCMCEfaCP4F/SjwD1gIWo5Ys/hw1OGMbEtI4JX2z3+k/WYe1eHtvDr11XmFEVYMM3haL3GXg51nelMPiNrO3yKnqD2KkuZZJO12FuA=
  - secure: Rykh84B3uSNvA6Sn6F+cNxVJvH0PVBy84XRzh/NHXbYDjeBO8XgdeQ4lhdn1JJAozFC8Oej/NON9xoorZ+qllFqeUmV4wDDEiVsjo8t1m6K9Du9XezrfNPqpk1RECQctZwitjLb7LiSVrxQhDP3FRUNu+alQvgf01/CgC1cvIMA=
  - secure: Gl2A5AEKYLqohJUsL6axquh+HqYGiZiDsImrsf8nV3gybi18+7XIwRRU4ry1OwjqXNlI5aJM4LNGGWtwYj/Wo7qYU5jJufPPzDGFNR4RilkE4C6Gnf4e+KgW0Hqcaakol1W8ZO73im9PQrqrtfF/LQyI3mXrPe/jIzB7KnqDqmc=
  - secure: DOMzGAK14qUpZ92wRz/PRW+mSBQQNTUgjCxMb8ZNdVN0sV4cphAngDDjpukMrphjADjJWbBDNGYAt7iSpuL9+v1zQQH+9daoVhhc+e96SnqgRW0WAdYzT+icou4qHSR2BnKQzwI5h/mx4nPPOaANAPi3uBQSth79TUmXeWrklBM=
  - secure: FgBtgZmpu48yR2FMTNQcUNYWGK8mmL3TPONfQe+MFYOImNn6h8TYDXL8EaI8w1J6eDoTyJNkmfsnUgowHeVCxyBGxZLfnrJmFPHucpUBWCWneWysrW68rmPSjmP62328hhy98KxAg5RfTZHhAJCgdhTRoQVePZIqhOle5jEPqJs=
